### ISSUE TITLE
PolyIR availability

### ISSUE THREAD

**Issue by mczac** [PolyPv/BeoRemote#1]
Hello, is it possible to repost PolyIR library for Arudino please?
thank you!

**Comment by PolyPv** [comment]
Hi. Unfortunately I do not have this library anymore, sorry. As far as I can remember it was basically a mix between [https://github.com/christianlykke9/Beomote](url) and [https://github.com/z3t0/Arduino-IRremote](url).

**Comment by mczac** [comment]
thanks
